#!/usr/bin/env node
var app = require('../app');
var debug = require('debug')('05-express-first-app:server');
var http = require('http');

/**
 * Get port from environement and store in express.
 */

var port = normalizePort(process.env.PORT || '8000');
app.set('port',port);
/**
 * create http server.
 */

var server = http.createServer(app);

/**
 * Listen on provided port, on all network interface.
 */

server.listen(port);
server.on('error',onError);
server.on('listening',onListening);
/**
 * Normalize a port int a number,string, or false.
 */

function normalizePort(val){
    var port = parseInt(val, 10);
}